version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: my_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Внутри docker-compose сервис db будет доступен по хосту "db"
      # Соберём DATABASE_URL на основе переменных
      DATABASE_URL: postgresql+psycopg2://myuser:mypassword@db:5432/mydb

volumes:
  db_data:
